### ISSUE TITLE
AttributeError: 'module' object has no attribute 'hashlittle2'

### ISSUE THREAD

**Issue by ate-it** [Vegoo89/AdtToObjParser#1]
Running getMapNames from CASCParser comes back with the error

AttributeError: 'module' object has no attribute 'hashlittle2'

0f00000018.idx
Gettting Encoding File
Encoding File found in IDX
Encoding File found in IDX
Length of file is: 79670115
Parsing Encoding
Gettting Root File
Found Root Location in Encoding
d18e4f0ed37a6d7fb8a303e86c182126
d68a66a2c228e4c39ffbc0654be3055b
Found Root Location in IDX
Found Root Location in IDX
Parsing Root FIle
Checking for flags: 00000000000000000000001000000010
Root Entries for current locale: 737585
Initialization Completed!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CASCParser.py", line 1039, in getMapNames
    mapdb2 = parseWoWFile('DBFilesClient\Map.db2', wowfolderpath)
  File "CASCParser.py", line 733, in parseWoWFile
    filehashname = Blizzhash(namefromlistfile)
  File "CASCParser.py", line 640, in Blizzhash
    stringhash = hex(jenkins96(fixedstring))
  File "CASCParser.py", line 625, in jenkins96
    c, b = jenkins.hashlittle2(string)
AttributeError: 'module' object has no attribute 'hashlittle2'

**Comment by Vegoo89** [comment]
Its part of jenkins-python module. Install it via pip.

**Comment by ate-it** [comment]
Indeed it is/was installed, it would appear that the other jenkins package uses the same namespaces and therefore causes interference, all sorted once jenkins is removed via pip
